// This file is generated by kconfig_compiler from okular.kcfg.
// All changes you do to this file will be lost.
#ifndef OKULAR_SETTINGS_H
#define OKULAR_SETTINGS_H

#include <core/okular_export.h>

#include <kconfigskeleton.h>
#include <kdebug.h>

#include <kuser.h>
namespace Okular {

class SettingsPrivate;

class OKULAR_EXPORT Settings : public KConfigSkeleton
{
  public:
    class EnumRenderMode
    {
      public:
      enum type { Inverted, Paper, Recolor, BlackWhite, COUNT };
    };
    class EnumMemoryLevel
    {
      public:
      enum type { Low, Normal, Aggressive, COUNT };
    };
    class EnumTextAntialias
    {
      public:
      enum type { Enabled, Disabled, COUNT };
    };
    class EnumGraphicsAntialias
    {
      public:
      enum type { Enabled, Disabled, COUNT };
    };
    class EnumSlidesTransition
    {
      public:
      enum type { BlindsHorizontal, BlindsVertical, BoxIn, BoxOut, Dissolve, GlitterDown, GlitterRight, GlitterRightDown, Random, Replace, SplitHorizontalIn, SplitHorizontalOut, SplitVerticalIn, SplitVerticalOut, WipeDown, WipeRight, WipeLeft, WipeUp, COUNT };
    };
    class EnumSlidesCursor
    {
      public:
      enum type { HiddenDelay, Visible, Hidden, COUNT };
    };
    class EnumExternalEditor
    {
      public:
      enum type { Custom, Kate, Kile, Scite, Emacsclient, COUNT };
    };

    static Settings *self();
    ~Settings();

    /**
      Set DebugDrawBoundaries
    */
    static
    void setDebugDrawBoundaries( bool v );

    /**
      Get DebugDrawBoundaries
    */
    static
    bool debugDrawBoundaries();

    /**
      Set DebugDrawAnnotationRect
    */
    static
    void setDebugDrawAnnotationRect( bool v );

    /**
      Get DebugDrawAnnotationRect
    */
    static
    bool debugDrawAnnotationRect();

    /**
      Set PaperColor
    */
    static
    void setPaperColor( const QColor & v );

    /**
      Get PaperColor
    */
    static
    QColor paperColor();

    /**
      Set HighlightImages
    */
    static
    void setHighlightImages( bool v );

    /**
      Get HighlightImages
    */
    static
    bool highlightImages();

    /**
      Set HighlightLinks
    */
    static
    void setHighlightLinks( bool v );

    /**
      Get HighlightLinks
    */
    static
    bool highlightLinks();

    /**
      Set ChangeColors
    */
    static
    void setChangeColors( bool v );

    /**
      Get ChangeColors
    */
    static
    bool changeColors();

    /**
      Set RenderMode
    */
    static
    void setRenderMode( int v );

    /**
      Get RenderMode
    */
    static
    int renderMode();

    /**
      Set RecolorForeground
    */
    static
    void setRecolorForeground( const QColor & v );

    /**
      Get RecolorForeground
    */
    static
    QColor recolorForeground();

    /**
      Set RecolorBackground
    */
    static
    void setRecolorBackground( const QColor & v );

    /**
      Get RecolorBackground
    */
    static
    QColor recolorBackground();

    /**
      Set BWThreshold
    */
    static
    void setBWThreshold( uint v );

    /**
      Get BWThreshold
    */
    static
    uint bWThreshold();

    /**
      Set BWContrast
    */
    static
    void setBWContrast( uint v );

    /**
      Get BWContrast
    */
    static
    uint bWContrast();

    /**
      Set MemoryLevel
    */
    static
    void setMemoryLevel( int v );

    /**
      Get MemoryLevel
    */
    static
    int memoryLevel();

    /**
      Set EnableCompositing
    */
    static
    void setEnableCompositing( bool v );

    /**
      Get EnableCompositing
    */
    static
    bool enableCompositing();

    /**
      Set EnableThreading
    */
    static
    void setEnableThreading( bool v );

    /**
      Get EnableThreading
    */
    static
    bool enableThreading();

    /**
      Set TextAntialias
    */
    static
    void setTextAntialias( int v );

    /**
      Get TextAntialias
    */
    static
    int textAntialias();

    /**
      Set GraphicsAntialias
    */
    static
    void setGraphicsAntialias( int v );

    /**
      Get GraphicsAntialias
    */
    static
    int graphicsAntialias();

    /**
      Set SlidesAdvance
    */
    static
    void setSlidesAdvance( bool v );

    /**
      Get SlidesAdvance
    */
    static
    bool slidesAdvance();

    /**
      Set SlidesAdvanceTime
    */
    static
    void setSlidesAdvanceTime( uint v );

    /**
      Get SlidesAdvanceTime
    */
    static
    uint slidesAdvanceTime();

    /**
      Set SlidesLoop
    */
    static
    void setSlidesLoop( bool v );

    /**
      Get SlidesLoop
    */
    static
    bool slidesLoop();

    /**
      Set SlidesBackgroundColor
    */
    static
    void setSlidesBackgroundColor( const QColor & v );

    /**
      Get SlidesBackgroundColor
    */
    static
    QColor slidesBackgroundColor();

    /**
      Set SlidesTransition
    */
    static
    void setSlidesTransition( int v );

    /**
      Get SlidesTransition
    */
    static
    int slidesTransition();

    /**
      Set SlidesCursor
    */
    static
    void setSlidesCursor( int v );

    /**
      Get SlidesCursor
    */
    static
    int slidesCursor();

    /**
      Set SlidesShowProgress
    */
    static
    void setSlidesShowProgress( bool v );

    /**
      Get SlidesShowProgress
    */
    static
    bool slidesShowProgress();

    /**
      Set SlidesShowSummary
    */
    static
    void setSlidesShowSummary( bool v );

    /**
      Get SlidesShowSummary
    */
    static
    bool slidesShowSummary();

    /**
      Set SlidesPencilColor
    */
    static
    void setSlidesPencilColor( const QColor & v );

    /**
      Get SlidesPencilColor
    */
    static
    QColor slidesPencilColor();

    /**
      Set SlidesTransitionsEnabled
    */
    static
    void setSlidesTransitionsEnabled( bool v );

    /**
      Get SlidesTransitionsEnabled
    */
    static
    bool slidesTransitionsEnabled();

    /**
      Set SlidesScreen
    */
    static
    void setSlidesScreen( int v );

    /**
      Get SlidesScreen
    */
    static
    int slidesScreen();

    /**
      Set ObeyDRM
    */
    static
    void setObeyDRM( bool v );

    /**
      Get ObeyDRM
    */
    static
    bool obeyDRM();

    /**
      Set ChooseGenerators
    */
    static
    void setChooseGenerators( bool v );

    /**
      Get ChooseGenerators
    */
    static
    bool chooseGenerators();

    /**
      Set ShowOSD
    */
    static
    void setShowOSD( bool v );

    /**
      Get ShowOSD
    */
    static
    bool showOSD();

    /**
      Set DisplayDocumentTitle
    */
    static
    void setDisplayDocumentTitle( bool v );

    /**
      Get DisplayDocumentTitle
    */
    static
    bool displayDocumentTitle();

    /**
      Set UseKTTSD
    */
    static
    void setUseKTTSD( bool v );

    /**
      Get UseKTTSD
    */
    static
    bool useKTTSD();

    /**
      Set WatchFile
    */
    static
    void setWatchFile( bool v );

    /**
      Get WatchFile
    */
    static
    bool watchFile();

    /**
      Set ExternalEditor
    */
    static
    void setExternalEditor( int v );

    /**
      Get ExternalEditor
    */
    static
    int externalEditor();

    /**
      Set ExternalEditorCommand
    */
    static
    void setExternalEditorCommand( const QString & v );

    /**
      Get ExternalEditorCommand
    */
    static
    QString externalEditorCommand();

    /**
      Set ShowLeftPanel
    */
    static
    void setShowLeftPanel( bool v );

    /**
      Get ShowLeftPanel
    */
    static
    bool showLeftPanel();

    /**
      Set SplitterSizes
    */
    static
    void setSplitterSizes( const QList<int> & v );

    /**
      Get SplitterSizes
    */
    static
    QList<int> splitterSizes();

    /**
      Set CurrentPageOnly
    */
    static
    void setCurrentPageOnly( bool v );

    /**
      Get CurrentPageOnly
    */
    static
    bool currentPageOnly();

    /**
      Set GroupByAuthor
    */
    static
    void setGroupByAuthor( bool v );

    /**
      Get GroupByAuthor
    */
    static
    bool groupByAuthor();

    /**
      Set GroupByPage
    */
    static
    void setGroupByPage( bool v );

    /**
      Get GroupByPage
    */
    static
    bool groupByPage();

    /**
      Set FilterBookmarks
    */
    static
    void setFilterBookmarks( bool v );

    /**
      Get FilterBookmarks
    */
    static
    bool filterBookmarks();

    /**
      Set SyncThumbnailsViewport
    */
    static
    void setSyncThumbnailsViewport( bool v );

    /**
      Get SyncThumbnailsViewport
    */
    static
    bool syncThumbnailsViewport();

    /**
      Set TocPageColumn
    */
    static
    void setTocPageColumn( bool v );

    /**
      Get TocPageColumn
    */
    static
    bool tocPageColumn();

    /**
      Set SidebarShowText
    */
    static
    void setSidebarShowText( bool v );

    /**
      Get SidebarShowText
    */
    static
    bool sidebarShowText();

    /**
      Set SidebarIconSize
    */
    static
    void setSidebarIconSize( uint v );

    /**
      Get SidebarIconSize
    */
    static
    uint sidebarIconSize();

    /**
      Set CenterFirstPageInRow
    */
    static
    void setCenterFirstPageInRow( bool v );

    /**
      Get CenterFirstPageInRow
    */
    static
    bool centerFirstPageInRow();

    /**
      Set EditToolBarPlacement
    */
    static
    void setEditToolBarPlacement( int v );

    /**
      Get EditToolBarPlacement
    */
    static
    int editToolBarPlacement();

    /**
      Set ShowScrollBars
    */
    static
    void setShowScrollBars( bool v );

    /**
      Get ShowScrollBars
    */
    static
    bool showScrollBars();

    /**
      Set ViewColumns
    */
    static
    void setViewColumns( uint v );

    /**
      Get ViewColumns
    */
    static
    uint viewColumns();

    /**
      Set ViewRows
    */
    static
    void setViewRows( uint v );

    /**
      Get ViewRows
    */
    static
    uint viewRows();

    /**
      Set TrimMargins
    */
    static
    void setTrimMargins( bool v );

    /**
      Get TrimMargins
    */
    static
    bool trimMargins();

    /**
      Set ViewContinuous
    */
    static
    void setViewContinuous( bool v );

    /**
      Get ViewContinuous
    */
    static
    bool viewContinuous();

    /**
      Set ViewMode
    */
    static
    void setViewMode( uint v );

    /**
      Get ViewMode
    */
    static
    uint viewMode();

    /**
      Set ZoomMode
    */
    static
    void setZoomMode( uint v );

    /**
      Get ZoomMode
    */
    static
    uint zoomMode();

    /**
      Set ZoomFactor
    */
    static
    void setZoomFactor( double v );

    /**
      Get ZoomFactor
    */
    static
    double zoomFactor();

    /**
      Set IdentityAuthor
    */
    static
    void setIdentityAuthor( const QString & v );

    /**
      Get IdentityAuthor
    */
    static
    QString identityAuthor();

    /**
      Set SearchCaseSensitive
    */
    static
    void setSearchCaseSensitive( bool v );

    /**
      Get SearchCaseSensitive
    */
    static
    bool searchCaseSensitive();

    /**
      Set SearchFromCurrentPage
    */
    static
    void setSearchFromCurrentPage( bool v );

    /**
      Get SearchFromCurrentPage
    */
    static
    bool searchFromCurrentPage();

  protected:
    Settings();
    friend class SettingsHelper;

  private:
    SettingsPrivate *d;
};

}

#endif

