# #####################################################################
# Automatically generated by qmake (2.01a) ?? 2? 18 10:31:34 2010
# #####################################################################
TEMPLATE = 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config-okular.h \
    kdebug.h \
    plocale.h \
    settings.h \
    kbookmark.h
SOURCES += settings.cpp \
    kbookmark.cpp
